### ISSUE TITLE
"Malformed painter stack" error

### ISSUE THREAD

**Issue by tkcl81** [d0rianb/rtf-parser#7] opened 2024-02-23 17:28 UTC
I'm getting an error with this file: 
[sample.rtf.zip](https://github.com/d0rianb/rtf-parser/files/14388298/sample.rtf.zip)

Would it be possible to add some lossy mode, which would extract text despite potential parsing issues?

Thanks for all your work!

**Comment by d0rianb** [comment] 2024-02-25 20:11
When I run the test, I get a lexer error because the last character is not a `}` but a `\n`. I cannot reproduce the `Malformed painter` stack issue. I will address the last char issue in the next commits.  
As for the lossy mode, it will be hard to get it down because the text is not easily distinguishable from the arguments of the control words.

**Comment by d0rianb** [comment] 2024-03-09 13:57
Fixed in 11524852a8385b78b7371b57f1d542fcd00ca8a7

**Closed as completed by d0rianb** 2024-03-09 13:57 UTC
