### ISSUE TITLE
RTF Error due to finding Ignorable Destinations

### ISSUE THREAD

**Issue by pvichivanives** [d0rianb/rtf-parser#9] opened 2024-03-11 23:48 UTC
Some RTF files fail because of ignorable destinations

From my findings, it seems to be because of the following pattern found where there is a. new line between the opening bracket and the ignorable destination:

(Token::OpeningBracket, Token::PlainText("\r\n"),Token::IgnorableDestination)

Which would also suggest that this should be another issue

(Token::OpeningBracket, Token::CRLF,Token::IgnorableDestination)

**Comment by d0rianb** [comment] 2024-03-12 08:58
Do you have any RTF sample so I can reproduce this issue ?
Moreover, which version are you using ? There should not be any `Token::PlainText("\r\n")` since the 0.1.9

**Comment by d0rianb** [comment] 2024-03-14 08:40
I've implemented changes in 53e30c027e71e7972393b2ae37fa7c775814eb1c concerning the parsing of ignore groups, to take newlines into account. I'm waiting for your examples to run properly before closing this issue.

**Comment by pvichivanives** [comment] 2024-03-16 00:29
I think I was on 0.17 at the time when I initially found it. I've Generated a new simple one that should follow the same pattern as the issue I found.
[rtf-error.zip](https://github.com/d0rianb/rtf-parser/files/14621778/rtf-error.zip)

**Comment by d0rianb** [comment] 2024-03-18 11:08
I tested your files. The ignorable destination issue has been fixed by 53e30c027e71e7972393b2ae37fa7c775814eb1c. However, I have noticed another bug due to the presence of a `\stylesheet`. In the last commit (8cc5a9248a3f756ff443206d3cf5ce81ed4c140a), I have added a condition to ignore this stylesheet, and I will maybe implement its parsing in the future.

**Closed as completed by d0rianb** 2024-03-18 11:08 UTC
